### ISSUE TITLE
Initial setup failing

### ISSUE THREAD

**Issue by lineville** [githubnext/blocks-template#28]
Hi blocks team 👋 ! I'm pretty excited about this project, and wanted to try it out for an internal project related to [elastic-machines](https://github.com/github/elastic-machines).

I was attempting the initial setup after creating a new repo from the template, I ran `yarn` and `yarn dev` and am seeing the following error message, and `http://localhost:4000/` isn't rendering anything. Any help here getting set-up would be awesome thanks! Let me know if you need any other information to troubleshoot this
![7342278B-1BD0-4662-91DB-1809FFE634FD](https://user-images.githubusercontent.com/25349044/163465023-c10d35f5-a411-4dae-9907-21d8787e3276.jpeg)

**Comment by lineville** [comment]
Just to follow up on this, I was able to resolve this issue with the following:

```bash
rm -rf node_modules
rm yarn.lock
yarn
yarn dev
```

It might be worth deleting the yarn.lock from the template project or potentially just updating some of the dependencies which I believe is the cause of the issue

**Comment by jaked** [comment]
thanks for the report! I'll run through the setup and try to reproduce.

You can also feel free to drop into #next-blocks Slack with any questions.

**Comment by StoneCypher** [comment]
@jaked - 

> You can also feel free to drop into #next-blocks Slack with any questions.

I would like to do this in re: #42, but I'm not able to locate the relevant slack.  Please advise
