### ISSUE TITLE
Curious, have you talked to Joel Spolsky about this?

### ISSUE THREAD

**Issue by jeffabailey** [githubnext/blocks-template#41]
If not, this might be a great collaboration opportunity.

https://blockprotocol.org/

**Comment by idan** [comment]
They reached out and we are planning to talk :D

Block Protocol and GitHub blocks have a lot of overlap, but they're also aiming for an industrywide standard, and I'm not sure that it makes sense for us to deal with the added complexity (vs designing for GitHub's platform). We'll talk with them and see!

**Comment by jeffabailey** [comment]
Awesome! 🎉

It doesn't hurt to ask.
